[package]
name = "wok-fips"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
fips-message = { path = "../fips-message" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
wok-relay = { path = "../wok-relay" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
fips = { git = "https://github.com/jmcorgan/fips.git", rev = "9a2b85cd4f511c978de1b028d6124115f64ad7a8" }
libc.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
secp256k1.workspace = true
serde_json.workspace = true
tempfile.workspace = true
wok-db = { path = "../wok-db" }
wok-event = { path = "../wok-event" }
