use std::sync::atomic::{AtomicU64, Ordering};

#[derive(Default)]
pub struct Metrics {
    pub active_connections: AtomicU64,
    pub authenticated_connections: AtomicU64,
    pub written_events_total: AtomicU64,
    pub ephemeral_events_total: AtomicU64,
    pub dup_events_total: AtomicU64,
    pub rejected_events_total: AtomicU64,
    pub auth_challenges_sent_total: AtomicU64,
    pub auth_success_total: AtomicU64,
    pub auth_failure_total: AtomicU64,
    pub slow_client_terminations: AtomicU64,
    pub abuse_connection_rejections: AtomicU64,
    pub abuse_event_rate_rejections: AtomicU64,
    pub abuse_req_rate_rejections: AtomicU64,
    pub abuse_count_rate_rejections: AtomicU64,
    pub abuse_pow_rejections: AtomicU64,
    pub abuse_query_cost_rejections: AtomicU64,
    pub abuse_query_concurrency_rejections: AtomicU64,
    pub abuse_pubkey_quota_rejections: AtomicU64,
    pub client_event: AtomicU64,
    pub client_req: AtomicU64,
    pub client_count: AtomicU64,
    pub client_close: AtomicU64,
    pub client_auth: AtomicU64,
    pub relay_event: AtomicU64,
    pub relay_eose: AtomicU64,
    pub relay_ok: AtomicU64,
    pub relay_notice: AtomicU64,
    pub relay_closed: AtomicU64,
}

impl Metrics {
    pub fn render(&self) -> String {
        let g = |n: &AtomicU64| n.load(Ordering::Relaxed);
        format!(
            concat!(
                "# HELP wok_active_connections Current WebSocket/Unix connections\n",
                "# TYPE wok_active_connections gauge\n",
                "wok_active_connections {}\n",
                "# TYPE wok_authenticated_connections gauge\n",
                "wok_authenticated_connections {}\n",
                "# TYPE wok_written_events_total counter\n",
                "wok_written_events_total {}\n",
                "# TYPE wok_ephemeral_events_total counter\n",
                "wok_ephemeral_events_total {}\n",
                "# TYPE wok_dup_events_total counter\n",
                "wok_dup_events_total {}\n",
                "# TYPE wok_rejected_events_total counter\n",
                "wok_rejected_events_total {}\n",
                "# TYPE wok_auth_challenges_sent_total counter\n",
                "wok_auth_challenges_sent_total {}\n",
                "# TYPE wok_auth_success_total counter\n",
                "wok_auth_success_total {}\n",
                "# TYPE wok_auth_failure_total counter\n",
                "wok_auth_failure_total {}\n",
                "# TYPE wok_slow_client_terminations_total counter\n",
                "wok_slow_client_terminations_total {}\n",
                "# TYPE wok_abuse_rejections_total counter\n",
                "wok_abuse_rejections_total{{reason=\"connection_rate\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"event_rate\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"req_rate\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"count_rate\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"pow\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"query_cost\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"query_concurrency\"}} {}\n",
                "wok_abuse_rejections_total{{reason=\"pubkey_storage_quota\"}} {}\n",
                "# TYPE wok_client_messages_total counter\n",
                "wok_client_messages_total{{type=\"EVENT\"}} {}\n",
                "wok_client_messages_total{{type=\"REQ\"}} {}\n",
                "wok_client_messages_total{{type=\"COUNT\"}} {}\n",
                "wok_client_messages_total{{type=\"CLOSE\"}} {}\n",
                "wok_client_messages_total{{type=\"AUTH\"}} {}\n",
                "# TYPE wok_relay_messages_total counter\n",
                "wok_relay_messages_total{{type=\"EVENT\"}} {}\n",
                "wok_relay_messages_total{{type=\"EOSE\"}} {}\n",
                "wok_relay_messages_total{{type=\"OK\"}} {}\n",
                "wok_relay_messages_total{{type=\"NOTICE\"}} {}\n",
                "wok_relay_messages_total{{type=\"CLOSED\"}} {}\n",
            ),
            g(&self.active_connections),
            g(&self.authenticated_connections),
            g(&self.written_events_total),
            g(&self.ephemeral_events_total),
            g(&self.dup_events_total),
            g(&self.rejected_events_total),
            g(&self.auth_challenges_sent_total),
            g(&self.auth_success_total),
            g(&self.auth_failure_total),
            g(&self.slow_client_terminations),
            g(&self.abuse_connection_rejections),
            g(&self.abuse_event_rate_rejections),
            g(&self.abuse_req_rate_rejections),
            g(&self.abuse_count_rate_rejections),
            g(&self.abuse_pow_rejections),
            g(&self.abuse_query_cost_rejections),
            g(&self.abuse_query_concurrency_rejections),
            g(&self.abuse_pubkey_quota_rejections),
            g(&self.client_event),
            g(&self.client_req),
            g(&self.client_count),
            g(&self.client_close),
            g(&self.client_auth),
            g(&self.relay_event),
            g(&self.relay_eose),
            g(&self.relay_ok),
            g(&self.relay_notice),
            g(&self.relay_closed),
        )
    }
}
