db = "./strfry-db/"

dbParams {
    maxreaders = 256
    mapsize = 10995116277760
    noReadAhead = false
}

events {
    maxEventSize = 65536
    rejectEventsNewerThanSeconds = 900
    rejectEventsOlderThanSeconds = 94608000
    rejectEphemeralEventsOlderThanSeconds = 60
    ephemeralEventsLifetimeSeconds = 300
    maxNumTags = 2000
    maxTagValSize = 1024
}

relay {
    bind = "127.0.0.1"
    port = 7777
    auth {
        enabled = true
        serviceUrl = ""
        restrictedReadKinds = "4, 1059"
        restrictReadToInvolvedPubkey = true
    }
    info {
        name = "wok"
        description = "This is a wok instance."
        nips = ""
    }
    maxWebsocketPayloadSize = 131072
    maxFilterLimit = 500
    maxFilterLimitCount = 1000000
    maxSubsPerConnection = 200
    maxPendingOutboundBytes = 33554432
    negentropy {
        enabled = true
    }
    unix {
        enabled = false
        path = "./strfry-db/wok.sock"
        mode = 384
        maxFrameBytes = 131072
    }
}
